#!/usr/bin/env bash
# Generate a host-local tool pins file for the Software Factory (agents-3g6).
#
# agents-7bj made tool pinning FAIL-CLOSED: every trusted host-side tool (bwrap, gh, bd,
# git, semgrep, gitleaks, node, npm, npx, and the engine binaries pi, claude, agentapi)
# must carry a sha256 pin or a real run is refused (deepseek has no CLI binary; agents-mhv7).
# bwrap heads the list: it delivers the OS sandbox itself, so an unpinned bwrap makes the
# host read as unable to sandbox (agents-28nn). The
# repo `tools.yaml` ships the format with the pins commented out, because a binary's hash
# is host-specific and cannot live in a shared repo. This helper writes the host's actual
# pins to a host-local file that the factory reads via the FACTORY_TOOL_PINS env var (which
# is merged OVER tools.yaml by lib/tool_pins.load_tool_pins).
#
# Usage:
#   tools/generate-tool-pins.sh [OUT] [--lookup-path DIRS]
#   export FACTORY_TOOL_PINS="$HOME/.config/factory/tools.pins.yaml"
#
# THE LOOKUP NEVER ASKS THE SHELL WHAT A NAME MEANS (agents-28nn rounds 2-3, review P1s).
# The hash this script writes IS the vouch for the binary, so the binary's provenance is
# the whole game. Two shell-state attacks are closed here:
#   round 2: `command -v` across the inherited PATH let an earlier CI step plant a fake
#     tool (one $GITHUB_PATH line) and have this script HASH AND PIN THE FAKE. The lookup
#     is therefore confined to a FIXED list of the standard system bin dirs (below), and
#     this script's OWN PATH is set to it before anything runs. Confinement beats a
#     vendored digest because the system dirs are root-owned image content: planting a
#     binary there requires root, while a vendored digest would have to be regenerated by
#     the very pipeline whose integrity is in question.
#   round 3: `command -v` evaluates EXPORTED SHELL FUNCTIONS before the filesystem PATH,
#     so `export -f bwrap` (a BASH_FUNC_* line via $GITHUB_ENV) plus a planted ./bwrap in
#     the CWD made `command -v` answer the FUNCTION, and the script then hashed the
#     CWD-relative file and emitted a RELATIVE path that resolve_tool expanded from
#     whatever CWD the factory happened to run in (verified by construction). So the
#     lookup below tests each known bin dir EXPLICITLY ([ -f ] && [ -x ] — a filesystem
#     question shell state cannot answer for us), never `command -v`; the HASHER is
#     resolved the same way (it feeds the pin, so a planted or function-shadowed hasher
#     would vouch for anything); and any resolution that is not an ABSOLUTE path under
#     the confined dirs is REJECTED rather than emitted.
# A tool that exists only elsewhere (homebrew on macOS, nvm, ~/.local/bin) is reported
# NOT FOUND rather than trusted from an attacker-writable location; the operator passes
# those dirs EXPLICITLY via --lookup-path. The override is a command-line flag — never an
# inherited environment variable — because $GITHUB_ENV would let an earlier CI step set
# the variable and reopen the hole, while the invocation itself lives in the pinned
# action.yml. Relative dirs in --lookup-path are skipped: they can never produce an
# absolute pin path.
#
# STATED BOUNDARY, so the next reviewer does not have to rediscover it: bash resolves
# shell functions ahead of BUILTINS too, so an environment that can inject arbitrary
# BASH_FUNC_* variables could shadow echo/printf and corrupt this script's output. That
# capability is not a new hole in the pin — the same $GITHUB_ENV channel could pre-set
# FACTORY_TOOL_PINS at the workflow level or redirect this script's output path — so
# scrubbing functions here would be a half-defense dressed as a full one. The pin's
# anchor is that the CI environment an earlier step controls cannot WRITE the root-owned
# system dirs the lookup is confined to. Likewise the #!/usr/bin/env bash shebang
# resolves under the runner's PATH before line 1: a runner whose PATH selects the shell
# itself is image/runner provenance, a different bead.
#
# A tool that is not installed (e.g. the optional semgrep/gitleaks pre-pass scanners, or
# bwrap on a host that never sandboxes) is skipped with a comment: the factory only fails
# closed for a tool it actually resolves, so an absent tool stays absent rather than
# blocking the run. The same rule covers the ENGINE BINARIES (agents-28nn round 5): an
# engine that is not installed is skipped, but an INSTALLED engine whose directory was not
# passed via --lookup-path (engines usually install outside the system dirs, e.g.
# ~/.local/pi) is reported NOT FOUND and stays unpinned — and a factory run that dispatches
# it then REFUSES, because the adapter may only execute a pin-verified binary. Pass the
# engine's install dir explicitly, e.g.:
#   tools/generate-tool-pins.sh --lookup-path "$HOME/.local/bin"
#
# This is an explicit operator/runner step, never auto-run by the factory — the factory does
# not generate or relax pins on its own.
set -euo pipefail

# The known-safe lookup dirs: the standard system bin dirs, which an earlier CI step
# cannot reach through PATH manipulation ($GITHUB_PATH only PREPENDS directories; it
# cannot change what these directories contain).
SYSTEM_LOOKUP_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PIN_LOOKUP_PATH="$SYSTEM_LOOKUP_PATH"
OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --lookup-path)
      [ $# -ge 2 ] || { echo "error: --lookup-path needs a colon-separated directory list" >&2; exit 2; }
      # Operator dirs are PREPENDED to the system dirs, never a replacement: the script's
      # own plumbing (mkdir/dirname/date and the hasher) must keep resolving from the
      # system dirs, or the override would hand the hasher to the operator dir.
      PIN_LOOKUP_PATH="$2:$SYSTEM_LOOKUP_PATH"; shift 2 ;;
    --lookup-path=*)
      PIN_LOOKUP_PATH="${1#--lookup-path=}:$SYSTEM_LOOKUP_PATH"; shift ;;
    -*)
      echo "error: unknown flag $1" >&2; exit 2 ;;
    *)
      [ -z "$OUT" ] || { echo "error: unexpected extra argument $1" >&2; exit 2; }
      OUT="$1"; shift ;;
  esac
done
OUT="${OUT:-${HOME}/.config/factory/tools.pins.yaml}"

# From here on EVERY external command this script runs resolves only from the lookup
# dirs, so a PATH-planted namesake can neither be pinned nor feed the pin.
PATH="$PIN_LOOKUP_PATH"

# Resolve a name to an ABSOLUTE path by testing each confined lookup dir EXPLICITLY.
# Never `command -v`: it consults exported shell FUNCTIONS before the filesystem (an
# attacker who can export -f a namesake — or the hasher — would choose what gets hashed
# and what hash gets written) and answers with a BARE NAME for a function, which
# resolve_tool would later expand from the factory's CWD (agents-28nn round 3, review P1,
# proven by construction). A relative lookup dir can never yield an absolute pin path,
# so it is skipped — the emit-side absolute-path reject below is the hard backstop.
resolve_in_lookup() {
  local name="$1" dir
  local IFS=:
  for dir in $PIN_LOOKUP_PATH; do
    case "$dir" in
      /*) ;;
      *) continue ;;
    esac
    if [ -f "$dir/$name" ] && [ -x "$dir/$name" ]; then
      printf '%s/%s\n' "$dir" "$name"
      return 0
    fi
  done
  return 1
}

# The hasher feeds the pin, so it is resolved by the same explicit rule — a function or
# PATH-planted namesake for it would vouch for anything. No hasher in the confined dirs
# means no safe pin: fail loudly.
SHA256SUM="$(resolve_in_lookup sha256sum || true)"
SHA256_ARGS=()
if [ -z "$SHA256SUM" ]; then
  SHA256SUM="$(resolve_in_lookup shasum || true)"
  SHA256_ARGS=(-a 256)
fi
if [ -z "$SHA256SUM" ]; then
  echo "error: no sha256sum/shasum in the confined lookup dirs — cannot pin safely" >&2
  exit 2
fi
MKDIR="$(resolve_in_lookup mkdir || true)"
DIRNAME_BIN="$(resolve_in_lookup dirname || true)"
DATE="$(resolve_in_lookup date || true)"
if [ -z "$MKDIR" ] || [ -z "$DIRNAME_BIN" ] || [ -z "$DATE" ]; then
  echo "error: mkdir/dirname/date must resolve in the confined lookup dirs" >&2
  exit 2
fi

TOOLS="bwrap gh bd git semgrep gitleaks node npm npx pi claude agentapi"

"$MKDIR" -p "$("$DIRNAME_BIN" "$OUT")"
{
  echo "# Host-local Software Factory tool pins (agents-3g6)."
  echo "# Generated $("$DATE" -u +%Y-%m-%dT%H:%M:%SZ); consumed via FACTORY_TOOL_PINS (merged over tools.yaml)."
  echo "# Regenerate after any tool upgrade: tools/generate-tool-pins.sh"
  echo "# Lookup confined to: $PIN_LOOKUP_PATH (an inherited PATH is never trusted; agents-28nn round 2)"
  echo "# Resolution is explicit per-directory filesystem tests, never command -v: exported"
  echo "# shell functions and the CWD cannot influence what is hashed or emitted (agents-28nn round 3)"
  for tool in $TOOLS; do
    path="$(resolve_in_lookup "$tool" || true)"
    if [ -z "$path" ]; then
      echo "# $tool: not found in the pinned lookup dirs — no pin"
      continue
    fi
    case "$path" in
      /*) ;;
      *)
        # A non-absolute resolution can never be emitted: resolve_tool expands a relative
        # pin path from the factory's CWD, which is exactly the planted-payload chain.
        echo "error: $tool resolved to a non-absolute path ($path) — refusing to emit it" >&2
        exit 2 ;;
    esac
    # ${...%% *} splits the hasher's "<hash>  <path>" output with the shell itself, so no
    # external filter (awk) sits in the pin's path. The ${arr[@]+...} form keeps an empty
    # SHA256_ARGS legal under set -u on bash 3.2 (macOS).
    hash_line="$("$SHA256SUM" ${SHA256_ARGS[@]+"${SHA256_ARGS[@]}"} "$path")"
    hash="${hash_line%% *}"
    echo "$tool:"
    echo "  path: $path"
    echo "  sha256: $hash"
  done
} > "$OUT"
echo "Wrote tool pins to $OUT (lookup confined to: $PIN_LOOKUP_PATH)"
echo "Export it: export FACTORY_TOOL_PINS=\"$OUT\""
